[en]
title = "Marcos Turial"
weight = 1
LanguageName = "EN"
contentDir = "content/english"

[br]
title = "Marcos Turial"
description = "Um Engenheiro Química que ama dados, inteligência artificial e a natureza"
contentDir = "content/portuguese" 
weight = 2
LanguageName = "PT"
