  [[main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[main]]
  name = "Portfolio"
  weight = 200
  identifier = "portfolio"
  url = "/portfolio/"

  #[[main]]
  #name = "Posts"
  #weight = 300
  #identifier = "posts"
  #url = "/post/"

  [[main]]
  name = "About"
  weight = 400
  identifier = "about"
  url = "/about/"

  #[[main]]
  #name = "Certifications"
  #weight = 500
  #identifier = "certifications"
  #url = "/certifications/"
#
  #[[main]]
  #name = "Contact"
  #weight = 600
  #identifier = "contact"
  #url = "/contact/"
#
  #[[footer]]
  #name = "imprint"
  #weight = 700
  #identifier = "imprint"
  #url = "/imprint/"